org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental.native=true
kotlin.mpp.stability.nowarn=true

GROUP=com.hyeons-lab
VERSION_NAME=0.1.0-SNAPSHOT
